import{a as d,S as m,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();const p="44529920-2c5437e602f6361a7a48a154a";d.defaults.baseURL="https://pixabay.com/api/";async function f(s,t,e=40){const{data:l}=await d(`?key=${p}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${e}`);return l}const a={form:document.getElementById("search-form"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")},g=new m(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const t=s.map(e=>`
      <a href="${e.largeImageURL}" class="photo-card">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${e.likes}</p>
          <p class="info-item"><b>Views:</b> ${e.views}</p>
          <p class="info-item"><b>Comments:</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    `).join("");a.gallery.insertAdjacentHTML("beforeend",t),g.refresh()}let c="",i=1;a.form.addEventListener("submit",h);a.loadMoreBtn.addEventListener("click",b);async function h(s){if(s.preventDefault(),i=1,a.gallery.innerHTML="",a.loadMoreBtn.style.display="none",c=s.target.searchQuery.value.trim(),!c){n.error({title:"Error",message:"Empty input, please enter your query."});return}try{const{hits:t,totalHits:e}=await f(c,i);if(t.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again."});return}y(t),i*40>=e?(a.loadMoreBtn.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):a.loadMoreBtn.style.display="block",n.success({title:"Success",message:`Hooray! We found ${e} images.`})}catch(t){console.log(t),n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}async function b(s){i+=1;try{const{hits:t,totalHits:e}=await f(c,i);y(t),i*40>=e&&(a.loadMoreBtn.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}
//# sourceMappingURL=commonHelpers.js.map
